language: cpp
compiler: gcc
python: "2.7"
install:
- make vendor
- sudo pip install -r tests/mocks/requirements.txt --use-mirrors
before_script:
- python tests/mocks/rest_webservice.py &
script:
- make test
